list:
    path: /invoices
    controller: App\Controller\InvoiceListController::index

create:
    path: /create
    controller: App\Controller\InvoiceCreationController::index

edit:
    path: /edit/{id}
    controller: App\Controller\InvoiceEditController::index

